version: '3.7'

services:
  service_mongo_auth:
    image: mongo:latest
    container_name: service_mongo_auth
    restart: unless-stopped
    env_file: .env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGO_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD=$MONGO_PASSWORD
    ports:
      - 27018:27017
    volumes:
      - mongodb_data_container_auth:/data/db

  service_node_auth:
    build:
      context: .
      dockerfile: ./services-auth/Dockerfile.dev
      target: base
    volumes:
      - ./services-auth/src:/home/node/services-auth/src
      - ./services-auth/nodemon.json:/home/node/services-auth/nodemon.json
    container_name: service_node_auth
    env_file: .env
    environment:
      - MONGO_HOSTNAME=service_mongo_auth
    expose:
      - '3001'
    ports:
      - '3001:3000'
    command: npm run dev
    depends_on:
      - service_mongo_auth

  # mongo_express_payment:
  #   image: mongo-express
  #   container_name: mongo-express
  #   restart: unless-stopped
  #   environment:
  #     - ME_CONFIG_MONGODB_SERVER=service_mongo_auth
  #     - ME_CONFIG_MONGODB_PORT=27017
  #     - ME_CONFIG_MONGODB_ADMINUSERNAME=$MONGO_USERNAME
  #     - ME_CONFIG_MONGODB_ADMINPASSWORD=$MONGO_PASSWORD
  #   ports:
  #     - 8081:8081
  #   depends_on:
  #     - service_mongo_auth

volumes:
  mongodb_data_container_auth:
