FROM node:latest as base

WORKDIR /home/node/services-auth

COPY ./services-auth/package*.json ./

RUN npm i

COPY ./services-auth/ ./

FROM base as production

ENV NODE_PATH=./build

RUN npm run build